version: '3.8'

services:
  backend:
    build: .
    container_name: nest_backend
    ports:
      - '3000:3000' # Porta padrão
    env_file: .env
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: bd_agenda_cotad
    ports:
      - '27017:27017' 
    volumes:
      - ./data/db:/data/db